modLoader="javafml"
loaderVersion="[40,)"
license="GPLv3"

[[mods]]
modId="leatheroverhaul"
version="${file.jarVersion}"
displayName="Leather Overhaul"
logoFile="leatheroverhaul.png"
credits="BrokenKeyboard"
authors="BrokenKeyboard"
description='''Attempts to "fix" leather as a resource and improves leather armor by giving it unique gameplay mechanics.'''

[[dependencies.leatheroverhaul]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.leatheroverhaul]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"